[package]
name = "arch-audit"
version = "0.1.2"
authors = ["Andrea Scarpino <me@andreascarpino.it>"]
description = "An utility like pkg-audit for Arch Linux based on Arch CVE Monitoring Team data"
repository = "https://github.com/ilpianista/arch-audit"
license = "MIT"
readme = "README.md"
keywords = ["archlinux", "security"]

[[bin]]
name = "arch-audit"

[dependencies]
alpm = "^0.3"
clap = "2"
curl = "^0.3"
env_logger = "^0.3"
itertools = "^0.4"
log = "^0.3"
json = "^0.10"
select = "^0.3"
